# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Language',
            field=models.CharField(default='hin', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='Description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
