# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20160715_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='NoPredictions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movies',
            name='NoRating',
            field=models.IntegerField(default=0),
        ),
    ]
